sudo: false
language: php

php:
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer -V
  - composer install
  - composer require --dev friendsofphp/php-cs-fixer

script:
    - find . -path ./vendor -prune -o -type f -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
    - echo ${COMMIT_RANGE}
    - CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRTUXB "${COMMIT_RANGE}")
    - if ! echo "${CHANGED_FILES}" | grep -qE "^(\\.php_cs(\\.dist)?|composer\\.lock)$"; then IFS=$'\n' EXTRA_ARGS=('--path-mode=intersection' '--' ${CHANGED_FILES[@]}); fi
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then php php-cs-fixer fix . -v --dry-run --stop-on-violation --rules=@Symfony --using-cache=no "${EXTRA_ARGS[@]}"; fi
